### ISSUE TITLE
Clarification: any plans for GA before March 2018

### ISSUE THREAD

**Issue by VelinGeorgiev** [pnp/pnp#1]
#### Category
[ ] Enhancement
[ ] Bug
[x] Question

There is an ongoing discussion within my team and we would like to use 3.XX Version (and contribute to pnp if some roadblocks) for a new project that we already started, but the project release date is March 2018. In order to justify the use of beta library for that project I would like to ask for if any future plans for General Availability version rough release dates. Is there a chance the PnP 3.xx is GA before March 2018?

I know that it is too early for any dates, but some sort of information might help us to decide on whether we go with 3.XX and also contribute fixes.

Cheers,
Velin

**Comment by koltyakov** [comment]
+1 for the question

**Comment by patrick-rodgers** [comment]
3.0.0 sp-pnp-js is released now (3.0.1 is latest). We will continue to support sp-pnp-js (bug fixes, small updates) for at least 6 months after @pnp scoped packages are released.

Version 1 of the @pnp scoped packages will come likely in December of 2017 once I am back from family leave and can ensure my availability. Plus I need to get docs written, samples, new wiki for all the changes. Plus a migration guide :) 

My recommendation would be please submit any updates to sp-pnp-js in the 3.0.* stream. For new work starting in January 2018 we'll be encouraging folks to move over to the @pnp scoped packages. If you want to try out the betas now I just updated them earlier. They include a "bundle" that has all the depdendencies in one package for easy use - or you can deploy separately. Again I owe docs on transitioning that will lay things out clearly.

Another of my todo items is to put my list of personal todos into the issues list here tied to milestones to give folks a realistic timeline and visibility into what is being worked on.

HTH

**Comment by VelinGeorgiev** [comment]
Hey Patrick (@patrick-rodgers),

I should have looked at the current library packages.json ("version": "1.0.0-beta.2") before asking. What I actually wanted to ask is the current library e.g. scoped packages ("version": "1.0.0-beta.2"), but you gave me very clear answer.

Thanks a lot for that.

I am closing that issue. Feel free to reopen it, if we have to keep the feed live.

**Comment by patrick-rodgers** [comment]
Great, I know I need to get some docs written up to help folks understand the changes and timelines but balancing that family duties currently. Thanks for understanding, we'll get there :)
