### ISSUE TITLE
Documentation: logging\index.html

### ISSUE THREAD

**Issue by mpowney** [pnp/pnp#10]
I'm interested to understand how the static Logger class handles usage in multiple SPFx components on the same page. 

If we have a custom LogListener that's registered via the Logger's subscribe method, what is the scope of that subscription array? 

For example, if the custom LogListener is defined with data specific to the calling web part, will it's data ever be used if the Logger static class is called in another context, e.g. another SPFx web part on the same page?

I suspect this relates to how TypeScript defines singleton / static classes, and possibly bundling, so references to relevant Typescript / webpack / build doco may help.

**Comment by patrick-rodgers** [comment]
Each SPFx web part is itself a closure, meaning anything instantiated within that container is only present in that container. So your webparts wouldn't know that others were even using the same logging framework.

IF you were using the library outside of SPFx and for example including the files on a page via script tag then then everything is global for that page and your logging setup would be shared across the page.

Make sense?

**Comment by mpowney** [comment]
Yes thanks Patrick, that makes sense.
