### ISSUE TITLE
Setup guidance

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnp#11]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.0.2        ]

### Question
I was looking over the documentation and I was slightly confused as to the samples. On the page below one example initialized the object in the init whereas another just called directly using the object. What are the differences between these approaches or do they assume the init is always done?

https://github.com/pnp/pnp/blob/dev/packages/sp/docs/index.md 

Also what are the best practices around this? Should we always setup in the init? Do we need to do this in each component and sub-component or can we do it once at the top level and pass as a property?

Cheers,

Ray

**Comment by koltyakov** [comment]
Hey @raymondlittle100,

In the docs, you've mentioned, different scenarios are covered:

- Classic pages scripts
- Usage with SPFx web parts/extensions
- Usage in Node.js (server-side)

For general cases, no `sp.setup` is needed (with some exceptions, e.g. SharePoint 2013, where OData mode often should be switched to verbose). `onInit` is relevant for SPFx, not related to PnPjs setup. For Node.js authenticated fetch client should be provided in setup.

**Comment by raymondlittle100** [comment]
In my case I will be working with SPFx web parts and extensions so I'm guessing this isn't need?

**Comment by koltyakov** [comment]
In this case, this [setup](https://github.com/pnp/pnp/blob/dev/packages/sp/docs/index.md#getting-started-sharepoint-framework) should be followed.

Otherwise, the library can't understand web context.

The magic happening in this lines:

```typescript
sp.setup({
  spfxContext: this.context
});
```

**Comment by raymondlittle100** [comment]
Perfect thanks
