### ISSUE TITLE
Ability to determine if comments are enabled

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnp#12]
### Category
- [ x] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.0.2     ]

### Question
There are various methods for updating and interacting with modern pages, including the ability to enable and disable comments, however I can't see a way to check if comments are enabled or not. In my case I'm providing a wrapper UI to allow users to toggle comments on or off and I would like to be able to check what the current status of the page is first. I've looked but I can't see any way to do this.

**Comment by patrick-rodgers** [comment]
You can see if comments are disabled using the CommentsDisabled property on ListItem:

```TypeScript
    const g = await sp.web.lists.getByTitle("Site Pages").items.getById(13).select("CommentsDisabled").get();

    console.log(`CommentsDisabled: ${g.CommentsDisabled}`);
```

**Comment by raymondlittle100** [comment]
magic. I was trying this on the page not the list item. A nice improvement to the page API might be to have  a property since we have the ability to set it to either enabled or disabled

**Comment by patrick-rodgers** [comment]
Added a property to ClientSidePage commendsDisabled that is valid after the page is loaded.

**Comment by raymondlittle100** [comment]
@patrick-rodgers do you know if can you update the comments status in the same way when updating the page list item? I know you can use the comments enable/disable methods on the page but in my case I'm already updating the list and it would be nice to reduce the number of calls and toggle the comments settings when calling the 'validateUpdateListItem' method.

I tried setting up another 'ListItemFormUpdateValue' object for 'CommentsDisabled' but it errors saying there is no field in SharePoint.

Cheers

**Comment by patrick-rodgers** [comment]
I do not believe you can as I think that method does some other things under the hood.

**Comment by raymondlittle100** [comment]
Thanks. It was just to save doing an additional call into SharePoint
