### ISSUE TITLE
Ability to delete sections, columns and controls

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnp#13]
### Category
- [ x] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.0.2     ]

### Expected / Desired Behavior / Question
Looking over the client side pages functionality there is the ability to add new sections, columns and controls but there is nothing to delete them. This would be really useful

**Comment by patrick-rodgers** [comment]
You can manipulate the arrays using the standard array methods such as slice.

Obviously we can make things easier - what would that look like? Would each control/column etc. have a delete or remove? What should happen to controls in a section if I delete it - delete them or keep them somehow?

**Comment by raymondlittle100** [comment]
Ah never thought of that :). So if i remove the items from the array when the page save happens will that detect the sections/columns have gone and delete them?

In terms of controls its difficult but you could have a method with some overloads. The default could be there are deleted and you pass a flag to say false and it moves them to the first section. Alternatively the overload could be to pass a section and column where any controls would go instead of being deleted. What you think?

**Comment by patrick-rodgers** [comment]
Added a remove method to section, column, and part that will take them out of the collection.
