### ISSUE TITLE
Unable to add multiple columns to modern page

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnp#15]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.0.2      ]

### Expected 
Add multiple columns to a page to try and change it from a single column to a three column layout. Get a page and change the default column to have a factor of 4 then add two new columns with a factor of 4 and save the page.

### Observed Behavior
The code runs and the page appears to have the correct number of columns but each new column added seems to have an order of 1. When fetching the page again and inspecting the columns the middle one has a factor of undefined whereas the other two have a factor of 4.

### Steps to Reproduce
Fetch the page then run code when user selects an option in a custom UI

let columnFactor: CanvasColumnFactorType[] = [6,6];
    switch(option.key)
    {     
      case "Three":         
        columnFactor.length = 0
        columnFactor.push(4,4,4);
      break;
      case "ThirdRight":      
        columnFactor.length = 0
        columnFactor.push(8,4);
      break;
    }
        
    columnFactor.forEach((column, index) =>
    {
      if(index ==0)
      {
        this.page.sections[0].columns[0].factor = column;
      }
      else
      {
//this adds the new column but both new columns have the same order of 1, this is down to the code in the 'getNextOrder' function. The first column has an order of 0.5, the second column gets an order of 1 and the third also gets an order or 1 because the check says is the second column doesn't have a order of great than 1
        var newColumn = this.page.sections[0].addColumn(column);        
      }
    });      

    this.page.save().then(result =>
    {
      console.log(result);
    })

See screenshot of updated page in UI

![updatepagelayout](https://user-images.githubusercontent.com/23637375/36667703-b4429808-1ae6-11e8-9c75-9f4f7c848c32.PNG)

Data from page after changes have been applied, order looks ok but factor for column 1 is undefined

![columnfactoring](https://user-images.githubusercontent.com/23637375/36667921-83f26b50-1ae7-11e8-9053-988f069bd4e0.PNG)

**Comment by patrick-rodgers** [comment]
I get what you are saying - but where are the decimal column orders coming from? Is that something you are doing in your code?

Appreciate all the detail in the issues you're posting - makes it very easy to see and understand what is wrong. I can re-work the getNextOrder method to handle zero based ordering. Thanks!

**Comment by raymondlittle100** [comment]
I'm not touching the ordering I assumed it was SharePoint or the PnP library which was doing this. When inspect the sections after adding them, but before saving, I get 0,1 and 1. Once I reload the page and fetch the details again I get the screenshot attached
