### ISSUE TITLE
Set-PnPListItem 

### ISSUE THREAD

**Issue by elazar-b** [pnp/PnP#1903]
####Which PnP repository should you use to report the issue?####
PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
#### Category

[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Set-PnPListItem -List "test" -Identity $ConnectToSPs.Id -Values @{"Status" = "Failed" }
When requesting status change on page SharePoint
#### Observed Behavior
format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be 
explicitly requested.

#### Steps to Reproduce
Connect-PnPOnline -Url ........

$ConnectToSPs = Get-PnPListItem -List "test" | Where-Object { ($_)["Status"] -eq "Waiting" }
set-mailbox ......etc

Set-PnPListItem -List "test" -Identity $ConnectToSPs.Id -Values @{"Status" = "Failed" } 

error :
format-default : The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be 
explicitly requested.

**Comment by FranckyC** [comment]
Hi @elazar-b, this is a more PowerShell issue. Just catch the cmdlet result in a variable like `$item = Set-PnPlistItem`. Maybe [this article](https://sympmarc.com/2020/04/24/an-inconvenient-powershell-error-format-default-the-collection-has-not-been-initialized/) could help.

**Comment by elazar-b** [comment]
Thanks a lot - the solution helped
