### ISSUE TITLE
Why is this repository in this location?

### ISSUE THREAD

**Issue by moontear** [pnp/pnp#2]
So PnPJS was just officially announced: https://dev.office.com/blogs/introducing-pnpjs-client-side-libraries-for-office365

Everything links to this repository (pnp/pnp). Why is this repository here and not in https://github.com/sharepoint? Why is there a `vorpal` forked repository underneath pnp? This looks unprofessional and not very clean to me as I am used to having everything PnP related in the SharePoint repository.  
On the same note - why is PnPJS in "pnp/pnp" - shouldn't it at least be "PnPJS" as a repository name? This confuses new developers and old ones alike. Also it is completely unclear how PnPJS relates to the core library (https://github.com/SharePoint/PnP-JS-Core) - is it built on JS-Core? Is it relying on it?

Please move this repository to where all other Patterns and Practices repositories are and clear up dependencies so we know what is what.

**Comment by patrick-rodgers** [comment]
Hi @moontear - thanks for your feedback and interest in the library. The repo is here to match the scope under which we are releasing these libraries. Would encourage you to [check out the docs](https://pnp.github.io/pnp/) as well as the [transition guide](https://pnp.github.io/pnp/transition-guide.html) that discusses some of your questions. These are a new set of libraries that do not depend on or use sp-pnp-js, but much of the code is based on that previous work. You can also attend our [bi-weekly calls](https://aka.ms/sppnp-js-sig-call) where we discuss all of the client-side development work in SharePoint.

**Comment by PSchicht** [comment]
> Please move this repository to where all other Patterns and Practices repositories are and clear up dependencies so we know what is what.

Exactly this. I dont't understand why this is here. Does this superseed the https://github.com/SharePoint/PnP-JS-Core Lib?

Why is the doc so formatted differently?

**Comment by waldekmastykarz** [comment]
@moontear regarding the Vorpal fork: we use it in the Office 365 CLI where we had to fix some bugs, specifically for our case. It's an internal dependency that you shouldn't worry about.
