### ISSUE TITLE
Web part ordering

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnp#21]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.0.2     ]

### Expected 
Adding a new web part to a column and i would like to be able to force this to the top of the column i.e. if there are already 2 web parts in this column i would like to push my newly added web part to the top of the list.

### Observed Behavior
The web part is added but regardless of the control ordering the new web part is added to the end 

### Steps to Reproduce
Create a new page, set the column layout to 3 columns, add two columns to the RHS column and save and publish the page.

Run code based on the sample to fetch the page and add a new web part. Added a line of code to then get the new web part and set the order to a low value to try and force it to the top via setting order to 0.5

//was a little unsure but seem to get a column back not a web part
const newcolumn = this.page.sections[sectionNumber].columns[columnNumber].addControl(part);
    
//default position is new web part is added at the end so change position
this.page.sections[sectionNumber].columns[columnNumber].controls[column.controls.length-1].order = webPartIndex;

see output in debug window below
![webpartordering](https://user-images.githubusercontent.com/23637375/36905399-33af851e-1e2b-11e8-8cdc-a7329902ea71.PNG)

see output on the page after the save is done
![uipositionaftersaving](https://user-images.githubusercontent.com/23637375/36905821-3d747ffe-1e2c-11e8-8886-432e6e4cbf5e.PNG)

**Comment by patrick-rodgers** [comment]
This should work if you reorder the parts within the array. This is essentially a duplicate of #13 in a way, the idea that we should wrap and control the underlying array manipulation for controls and columns. Boils down to what should take precedence - you setting the .order property of a control or the physical order in the array. I am leaning towards physical order in the array because setting .order doesn't trigger anything and could be set to junk (nothing says in js you can't set it to "a" at runtime).

**Comment by raymondlittle100** [comment]
ah ok I'll try that

**Comment by patrick-rodgers** [comment]
Well in the next version as it will have the reindex code included before saving. That isn't present in the current library. I just published a beta version that should have all the fixes for the things you have been reporting. You can install is using `npm install @pnp/sp@beta`. Give that a try and most of the issues you've reported should now be resolved. If not you can reopen those issues and hopefully they can be resolved before we push the real version. Thanks!

**Comment by raymondlittle100** [comment]
I have tested the re-ordering by updating the array and this works fine so will use this approach for now. Thanks for all your help. 

Do you know when the new version will be released outside beta?

**Comment by patrick-rodgers** [comment]
Aiming for Monday, March 5.
