### ISSUE TITLE
@pnp\logging installation issues

### ISSUE THREAD

**Issue by RodCoder** [pnp/pnp#25]
Hi,

I'm currently migrating some code and was trying to use the storage functions in the pnp/common package. 

When executing this line: npm install @pnp\logging @pnp\common --save

I get the following issue: 
Could not install from "@pnp\logging" as it does not contain a package.json file.

Am I doing something wrong here?

Thanks,

Rodrigo

**Comment by koltyakov** [comment]
Hi Rod,

Looks like you're using reverse slash instead of `/`. Should be:

```bash
npm install @pnp/logging @pnp/common --save
```

**Comment by RodCoder** [comment]
Hi @koltyakov,

Thanks for the fast reply, just realised that... also submitted the change in the documentation.

**Comment by koltyakov** [comment]
Oh, I also found some places with this typo. I.e. https://github.com/pnp/pnp/blob/master/packages/config-store/docs/index.md
Thanks for finding this out!

**Comment by RodCoder** [comment]
No problem at all, I've noticed on at least three files. Guess you can take it from here :)

**Comment by koltyakov** [comment]
Once again, thanks! PRed with docs update will be updated on merge. Closing the issue.
