### ISSUE TITLE
Documentation: nodejs\sp-fetch-client.html

### ISSUE THREAD

**Issue by ryanalbert** [pnp/pnp#27]
I was unable to fetch data from my SharePoint Online site until I added the optional "realm" parameter to my new SPFetchClient object in the setup function. The error in Chrome before adding the realm:

Uncaught (in promise)
FetchError {name: "FetchError", message: "request to https://{site name}.sharepoint.com/vti_bin/client.svc failed, reason: Failed to fetch", type: "system", errno: undefined, code: undefined, …}

I believe this parameter should be included in the example, along with instructions for finding it: 
- Navigate to "https://{site name}-admin.sharepoint.com/_layouts/15/TA_AllAppPrincipals.aspx"
- Copy the string that follows the '@' in the App identifier column for the app that was granted permissions

Thanks for the work you've done!

**Comment by patrick-rodgers** [comment]
Will have a look, thanks for letting us know!

**Comment by patrick-rodgers** [comment]
Hi @ryanalbert - am circling back and catching up on issues. Just re-read this and noted you are getting this error in Chrome. The classes from the nodejs library are designed specifically to work in nodejs. You shouldn't need to use them in the browser. I am updating the docs to include the steps above, and appreciate your help. Thanks!
