### ISSUE TITLE
Enumerable Search Result Properties

### ISSUE THREAD

**Issue by Kizzik** [pnp/pnp#28]
### Category
- [X] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version
1.0.2

Can we make it so that the properties surfaced through the search results are returned as enumerable (see: https://github.com/pnp/pnp/blob/dev/packages/sp/src/search.ts#L372, currently set to false)? I'm trying to pass through my search results object to a React component using a spread operator, but because they are not enumerable they do not get passed through. It's a bit of a pain, because it means I either need to change the way data is passed through my React/Redux flow, or craft a copy of the results object myself before passing it through.

Is there value in setting them to non-enumerable that I am missing?

**Comment by patrick-rodgers** [comment]
Sure, that's an easy change and happy to do it. Did you have any interest in creating a PR for that change?

**Comment by Kizzik** [comment]
Awesome, thanks!

I'd love to, however I'm currently under the pump for a project so I'm not sure when I'd be able to get it done. I've never really worked on public projects before so it'd take me a little while to make sure I'm doing everything the right way. If I get an opportunity in a couple of weeks and it hasn't already been tackled, I'll definitely take a look!
