### ISSUE TITLE
Typescript error TS1005 during gulp build

### ISSUE THREAD

**Issue by DaveCalGH** [pnp/pnp#29]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnp/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.0.3     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Im running into some trouble using this library in an spfx webpart project. After running 
npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp --save

And adding my import to my ts file
import {sp} from "@pnp/sp";

The project then fails to build with gulp build. Many errors saying
"Error - Typescript - node_modules\@pnp\odata\src\queryable.d.ts (89,10): error TS1005: ',' expected.

Otherwise uninstalling the module my project builds and runs fine. Where do I wven start

**Comment by koltyakov** [comment]
Hi Dave,

What SPFx and especially TypeScript versions you are using?

I guess it can be an old version of TypeScript. On my end, the issue doesn't reproduce.

![image](https://user-images.githubusercontent.com/7816483/37076367-591323aa-21e7-11e8-9730-a2781f5b0732.png)

**Comment by DaveCalGH** [comment]
I did notice that there were 2 typescript versions using:
 npm list typescript versions

One package had a dependency on 2.2.2 and another at 2.4.2. I updated the 2.2.2 version to 2.4.2 and that seemed to fix it. I guess it was some kind of tsc bug.

**Comment by Nagarajan1605** [comment]
demo-pnp@0.0.1 D:\Demo
`-- @microsoft/sp-build-web@1.1.0
  `-- @microsoft/gulp-core-build-typescript@3.1.1
    +-- @microsoft/api-extractor@2.3.8
    | `-- typescript@2.4.2
    **`-- typescript@2.2.2**

How to update this typescript version

**Comment by koltyakov** [comment]
Hi @Nagarajan160, 

Unfortunately, there is no easy way but [this approach](https://pnp.github.io/pnpjs/documentation/SPFx-On-Premesis-2016/) only.
