### ISSUE TITLE
@pnp/graph: Error in graph.setup

### ISSUE THREAD

**Issue by olemp** [pnp/pnp#34]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.0.3]

### Expected / Desired Behavior / Question
The following setup should work in an SPFX webpart:

```typescript
import { graph } from "@pnp/graph";

public onInit(): Promise<void> {

  return super.onInit().then(_ => {

    // other init code may be present

    graph.setup({
      spfxContext: this.context
    });
  });
}
```

### Observed Behavior
I get the error `can not read fetchClientFactory of undefined`. 

Adding an empty graph object solves the issue:

```typescript

public onInit(): Promise<void> {

  return super.onInit().then(_ => {

    // other init code may be present

    graph.setup({
      spfxContext: this.context,
      graph: {}
    });
  });
}
```

**Comment by patrick-rodgers** [comment]
This is actually fixed in #32. I found it when I was doing that work. Thanks for reporting it.
