### ISSUE TITLE
adalfetchclient: Type definition is not found

### ISSUE THREAD

**Issue by estruyf** [pnp/pnp#45]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.0.3]

### Expected / Desired Behavior / Question

Typings reference for `types.d.ts` is not found. When transpiling TS to JS I get the following error: 

```node_modules/@pnp/nodejs/src/net/adalfetchclient.d.ts(1,22): error TS6053: File '/Users/user/project/packages/nodejs/src/net/types.d.ts' not found.```

<img width="764" alt="screenshot 2018-03-12 19 38 10" src="https://user-images.githubusercontent.com/2900833/37302833-ed9d1a64-262c-11e8-8337-6fe5c597a05a.png">

**Comment by patrick-rodgers** [comment]
That is the node client - do you mean to be running in node or browser?

**Comment by estruyf** [comment]
Running it in node

**Comment by patrick-rodgers** [comment]
Hmmm...in the file that reference is `/// <reference path="types.d.ts" />` to a local file - unsure what it is being rewritten and I am not able to duplicate currently.

**Comment by patrick-rodgers** [comment]
Confirmed that the types.d.ts isn't copied into the final package. Figuring out how best to address.
