### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'fetchClientFactory' of null

### ISSUE THREAD

**Issue by dhavalshah01** [pnp/pnp#48]
### Category
- [ ] Enhancement
- [ X] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 1.0.3

### Expected / Desired Behavior / Question
I am trying to make a simple graph api call to get the groups using new pnp js framework
( i tried that with the old framework as well and i still get the same error)

Dependencies in my package. json file is as below

```
"dependencies": {
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@pnp/common": "^1.0.3",
    "@pnp/graph": "^1.0.3",
    "@pnp/logging": "^1.0.3",
    "@pnp/odata": "^1.0.3",
    "@types/webpack-env": ">=1.12.1 <1.14.0",

  },
```

### Observed Behavior
I am getting the below error when i execute the code mentioned over here
https://pnp.github.io/pnp/graph/index.html

Uncaught (in promise) TypeError: Cannot read property 'fetchClientFactory' of null
    at GraphRuntimeConfigImpl.get [as fetchClientFactory] (graphlibconfig.ts:60)
    at new GraphHttpClient (graphhttpclient.ts:29)
    at Object.clientFactory (graphqueryable.ts:127)
    at pipeline.ts:222
    at new Promise (<anonymous>)
    at Function.PipelineMethods.send (pipeline.ts:203)
    at descriptor.value (pipeline.ts:252)
    at next (pipeline.ts:68)
    at pipeline.ts:252

### Steps to Reproduce

1. Create a new spfx webpart project 
2. run below npm command
npm install @pnp/logging @pnp/common @pnp/odata @pnp/graph --save

3. update the code in your webpart typescript file as below
```
  public onInit(): Promise<void> {
    return super.onInit().then(_ => {
      graph.setup({
        spfxContext: this.context
      });
    });
  }

public render(): void {
    graph.v1.groups.get().then(groups => {

      console.log(`Groups: ${JSON.stringify(groups, null, 4)}`);
      this.domElement.innerHTML = `Groups: <ul>${groups.map(g => `<li>${g.displayName}</li>`).join("")}</ul>`;
    });
  }
```
### Issue exist with the Old PNP framework as well

When i tried to run the similar code using sp-pnp-js framework, i get the same error. 

```
import pnp from "pnp";

pnp.graph.v1.groups.get().then((result)=>{
	console.log(result);
}).catch((error)=>{
	console.log(error);
})
```

**Comment by patrick-rodgers** [comment]
Hi @dhavalshah01 - this is actually fixed in the dev branch, was addressed in PR #32. You can check by pulling the the current beta version. Will be part of the next upcoming release. Thanks for reporting this!
