### ISSUE TITLE
Documentation: getting-started.html

### ISSUE THREAD

**Issue by Ma1984** [pnp/pnp#54]
I think that quite many people are using this library outside of SharePoint framework and need to specify baseURL

sp.setup({
    sp: {
        headers: {
            Accept: "application/json;odata=verbose",
        },
        baseUrl: "SharePoint URL"
    },
});

**Comment by patrick-rodgers** [comment]
Thanks, have added a section on this and it will publish with next version.

**Comment by koltyakov** [comment]
@Ma1984,

`baseUrl` is one of the possible options.
On On-Prem solutions I prefer creating web objects with implicit URL declaration:

```typescript
const web1 = new Web(`${_spPageContextInfo.siteAbsoluteUrl}/web1`);
const web2 = new Web(`${_spPageContextInfo.siteAbsoluteUrl}/web2`);
``` 

Cause it's a very frequent scenario when you need to rollup data from specific webs, etc.

`baseUrl` within `sp.setup` effect on default web construction - `sp.web`.

**Comment by Ma1984** [comment]
Unfortunatelly in our scenario we do not have a valid _spPageContextInfo

**Comment by koltyakov** [comment]
Yet, you know somehow the correct URLs for web to place to baseUrl. The goal of my comment was to show that `new Web('[web_absolute_url]')` let you working with different webs at the same time.

**Comment by patrick-rodgers** [comment]
I added both methods to the docs page...so we're covered either way.
