### ISSUE TITLE
Documentation: transition-guide.html

### ISSUE THREAD

**Issue by Ma1984** [pnp/pnp#55]
It would be nice to mention that HttpClient should be replaced by SPHttpClient

**Comment by patrick-rodgers** [comment]
Hi @Ma1984 - happy to make this update, can you give me a little more context to ensure I provide the right information? Do you mean if you are importing and using it directly in your solution?

**Comment by koltyakov** [comment]
If you used `HttpClient` from `sp-pnp-js` a lot it would be good to know that it was renamed to `SPHttpClient`. A transition to `@pnp/sp` assumes replacement of:

```typescript
import { HttpClient } from 'sp-pnp-js';
```

to the following import statement:

```typescript
import { SPHttpClient } from '@pnp/sp';
```

---

We could add something like this. Maybe?

**Comment by Ma1984** [comment]
Exactly. That information would save me some time :+1:

**Comment by patrick-rodgers** [comment]
Perfect, will update the docs, thanks!
