### ISSUE TITLE
Examples of HowTo use SPPnPJS

### ISSUE THREAD

**Issue by NPrice99** [pnp/pnp#9]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X ] Documentation gap/issue

Where can I find examples of how to use sppnpjs.  I have seen one example which uses knockout (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts), but no React examples.  As a minimum, As Microsoft use React themselves, I would have thought there should be at least a React version of the above example)

**Comment by koltyakov** [comment]
Hi Nigel,

Thanks for the question!

The library is really agnostic to the framework to use with. It can be used with any frontend library or framework.

PnPjs deals with promises. Any request is a promise. Results can be processed in a variety of ways. Mapped to DOM, or view-model or whatever.

Right now PnPjs is in the process of transition. It was formerly named [sp-pnp-js](https://github.com/SharePoint/PnP-JS-Core/wiki). Both projects are supported, but we're moving in the direction of bringing new features to this new repo. As it has a more solid vision and modular packages system.

But, currently, most of the examples and samples and recipes for sp-pnp-js are valid for PnPjs with small exceptions and the difference how to import the libs.

**Comment by NPrice99** [comment]
Hi

I appreciate the library is agnostic, that is good.

But as someone who is relatively new to React and who wants to use PnPjs I would hope there are examples / samples for me to study and use.

**Comment by koltyakov** [comment]
Are you going creating React apps as SPFx modern web parts or SPA/MPAs for classic pages deployment? 

With SPFx there are tons ([1](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples), [2](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples), [3](https://github.com/SharePoint/sp-dev-samples/tree/master/Samples/react-generic-app)) of examples, on community calls each time somebody shows something fancy and React is a frequent choice.

I would encourage searching for `sp-pnp-js` and `@pnp/sp` keywords over the repositories' links above. There are nice examples over there.

Also, almost any React with async data sources reference is relevant. And PnPjs REST API calls can be applied to abstract React examples too. My recommendation is to try React basics and PnPjs basics, then combine them together and ask some specific questions in our [Gitter channel](https://gitter.im/OfficeDev/PnP-JS-Core).

**Comment by NPrice99** [comment]
Thank you for your help @koltyakov That is great and just what I was looking for.  I am looking to create React apps as SPFx modern web parts.

**Comment by koltyakov** [comment]
Going to close the issue as answered.

**Comment by NPrice99** [comment]
Yes - go ahead.
